Feature/improve notification
naccoro/WASK-Android pull request #116
Opened 2020-12-09 02:04 UTC by SEONGGYU96

영구 알림 (Notification) 을 개선해보았습니다.

 ## 영어일 경우 day/days 구분
단순히 period가 1인 경우와 아닌 경우에 해당하는 string 리소스파일을 구분해두었습니다. 한글의 경우 두 리소스가 동일한 문자열을 가리키고, 영어인 경우 각 리소스는 day, days로 표기되어있습니다. 따라서 언어에 맞춰 단수/복수 구분을 하게 됩니다.

## 포그라운드 서비스의 재시작
앱을 사용하다보면 알 수 없는 원인으로 포그라운드 서비스가 종료되곤 합니다. 저 역시 WASK를 매일 사용하고 있는데 어쩌다 가끔, 한 달에 1~2회 정도 서비스가 종료되어있던 경험이 있습니다. 이 경우 앱을 실행해도 서비스는 살아나지 않고, 앱 내의 설정 창에 들어가 알림 스위치를 껐다가 켜야만 재실행됩니다.
아직 포그라운드 서비스가 종료되는 것을 100% 방지하기에는 어려우니, 종료되었을 때 이상하다고 느낀 사용자가 앱을 켜보기만해도 서비스를 재실행할 수 있도록 코드를 추가하였습니다.
해당 로직은 ServiceUtil에 추가해두었습니다.

2020-12-09 09:17 UTC, euzl approved these changes
확인했습니다!

2020-12-09 10:38 UTC, jaeryo2357 requested changes

2020-12-09 10:38 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/ui/main/MainContract.java
> +        void start(Context context);
Presenter에서 context를 참조하는 것은 안좋아보입니다! ㅠㅠ

저희 프로젝트는 테스트가 없지만, Presenter 테스트를 할 경우 context(Android FrameWork)랑 Presenter와 분리가 되지않아 Presenter Unit Test가 안좋다는 말을 들은 것 같아요!

View에서 Service를 실행시키는 함수를 만들고 presenter가 view의 함수를 호출하는 방식은 어떨까요?

2020-12-09 10:39 UTC, jaeryo2357 reviewed
이렇게 세세한점 오류난 점을 기억해주시고 수정해주시는 점 너무 존경합니다!

2020-12-09 12:37 UTC, SEONGGYU96 commented on app/src/main/java/com/naccoro/wask/ui/main/MainContract.java
> +        void start(Context context);
아 그렇군요? 그런데 저희 Presenter 에 포함된 많은 메서드들이 이미 Context를 참조하고 있습니다... 이런 경우는 어떻게 처리해야할까요? 기존 메서드들 보고 되는 줄 알고 했네요..

2020-12-09 12:41 UTC, Gomyo reviewed
다시 알림받기 위해 우선 대기하겠습니다!

2020-12-09 12:52 UTC, Gomyo approved these changes

2020-12-09 12:54 UTC, SEONGGYU96 commented on app/src/main/java/com/naccoro/wask/ui/main/MainPresenter.java
>      /**
@jaeryo2357 요렇게 변경했습니다 !
브랜치를 새로 파서 이렇게 되어있는 다른 메서드들도 수정해보겠습니다

2020-12-11 07:50 UTC, jaeryo2357 approved these changes

2020-12-11 07:50 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/ui/main/MainPresenter.java
> +        ServiceUtil.initForegroundService(WaskApplication.getApplication(), period);
엇 ㅠㅠㅠ 

MainContract.View {
   ...
   public void initForegroundService(int period);
}

public class MainActivity implements MainContract.View {
     public void initForegroundService(int period) {
           ServiceUtil.initForegroundService(this, period);
     }
}

이런식으로 변경하는 것이 좋아보입니다!. presenter에서 context를 아예 분리하는 것이 좋아보입니다!

2020-12-11 07:54 UTC, merged