Feature/setting activity
naccoro/WASK-Android pull request #19
Opened 2020-08-07 07:33 UTC by jaeryo2357

### #8 설정 엑티비티 작성

**구현**

- Main MVP 구조 
   - SettingAcitivty 이동하는 함수 구현
- Setting MVP 구조
   - UI 관련 View 로직은 90% 구현 완료
   
**미구현**
   - Settting Presenter에서 설정 값 저장하는 로직 구현해야 함!!

       ```java
            /**
              * 사용자가 Foregorund Alert Visible Switch의 값을 변경했을 때
              * @param value : 변경된 값 
              */
             @Override
              public void changeAlertVisibleSwitch(boolean value) {
                  //여기서 구현
               }
       ```
   - Wheel DataPicker PR이 merge가 안되어 일자를 선택하는 Dialog Custom View 미구현
   - 각 설정 값(ex) 1일, 3일, 소리+진동)에 대한  UI Widget은 xml에서 구현되어 있지만 이후 #9 issue에서 구현하면 될듯!

### 화면

 <img src="https://user-images.githubusercontent.com/33657541/89620509-b9c65e00-d8ca-11ea-9f05-b760f67803f4.png" width="300">
 <img src="https://user-images.githubusercontent.com/33657541/89620509-b9c65e00-d8ca-11ea-9f05-b760f67803f4.png" width="300">
 <img src="https://user-images.githubusercontent.com/33657541/89620512-bb902180-d8ca-11ea-93f7-c3b51f9f73ec.png" width="300">

2020-08-07 10:07 UTC, euzl requested changes
MVP를 적용해버리셨다..!!

2020-08-07 10:07 UTC, euzl commented on app/src/main/res/values/styles.xml
> +        <item name="android:colorControlActivated">#ffffff</item>
`@android:color/white` 사용하시면 될 것 같습니다

2020-08-07 10:07 UTC, euzl commented on app/src/main/res/values/colors.xml
> +    <color name="waskAccentFont">#597afb</color>
`waskBlue` 로 사용해도 될 것 같아요!

2020-08-07 10:07 UTC, euzl commented on app/src/main/res/layout/activity_setting.xml
> +            android:textSize="17sp"
testSize 도 dimen 이용하면 좋을 것 같습니다

2020-08-07 10:07 UTC, euzl commented on app/src/main/res/layout/activity_setting.xml
> +        android:id="@+id/replacement_cycle_alert_layout"
wask 컨벤션에 맞추면  `android:id="@+id/constraintlayout_replacement_cycle_alert" `이 맞을 것 같습니다!
**요소이름_사용처** 이렇게요!!

2020-08-07 10:07 UTC, euzl commented on app/src/main/res/layout/activity_setting.xml
> +        android:id="@+id/replacement_cycle_alert_layout"
다른 id 들도 부탁드려용

2020-08-07 10:07 UTC, euzl commented on app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
> +        replacementCycleAlertLabel = findViewById(R.id.mask_replacement_cycle_alert);
44~61번째 줄은 initView() 메서드를 만들어서 호출하면 더 좋을 것 같습니다!

2020-08-07 10:07 UTC, euzl commented on app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
> +    TextView replacementCycleAlertLabel;
클래스의 멤버 변수는 private 안 적어도 되나요? (궁금해서 질문합니다!!)

2020-08-07 10:07 UTC, euzl commented on app/src/main/res/layout/activity_setting.xml
> +
정확한 부분은 모르겠지만 설정액티비티 내부 배경색상  `@android:color/white` 로 변경부탁드려요..!!

2020-08-07 19:55 UTC, ethan-223 approved these changes
유진님이 상당히 디테일하게 피드백해주셔서 저는 따로 남길 게 없습니다 ! 뷰가 깔끔하게 나왔네요 !

2020-08-07 19:55 UTC, SEONGGYU96 commented on app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
> +    TextView replacementCycleAlertLabel;
외부에서 접근할 일이 없으면 최대한 private으로 해야할 것 같습니다 !

2020-08-07 19:55 UTC, SEONGGYU96 commented on app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
> +                    int cycleValue = 0;
//Todo: 주석을 사용하면 조금 더 보기에 좋을 것 같습니다 !

2020-08-07 19:55 UTC, SEONGGYU96 commented on app/src/main/res/layout/activity_setting.xml
> +            android:textSize="17sp"
dimen을 사용한다는 것이 무슨 뜻인가요?.?

2020-08-08 04:08 UTC, euzl commented
> @SEONGGYU96 왜인지는 모르겠는데 메일엔 알림이 오고 여기서는 댓글이 안 보이네요..!

dimen을 사용하자는 말은 크기 리소스(/res/values/dimens.xml)에 등록해서 `@dimen/<이름>` 으로 사용하자는 뜻이었습니다
http://ankyu.entersoft.kr/Lecture/android/resource_05.asp

2020-08-08 04:11 UTC, euzl approved these changes
#9 에 말하신 부분은 오늘은 못할 것 같습니다..!😥

2020-08-08 04:18 UTC, jaeryo2357 commented
자세히 말씀해주셔서 감사합니다!.. 제가 아직 컨벤션에 대한 정리가 미흡한것 같네요. 
다음부터는 컨벤션에 대한 지적이 없게끔 하겠습니다. ㅠㅠ

2020-08-08 04:52 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
> +    TextView replacementCycleAlertLabel;
위젯 멤버변수들은 `private`를 적어야 하는 것 같아요! 외부에서 접근을 할때 직접 접근하지 않고 함수로 접근을 유도하는 것 같습니다. 그래서 유진님 의견이 맞습니다.

2020-08-08 05:54 UTC, zoonun approved these changes
dimen이 css 개념이네요! 새로운 것을 알아갑니다.

2020-08-08 15:55 UTC, euzl commented on app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
> +    TextView replacementCycleAlertLabel;
그렇군요 알려주셔서 감사합니다

2020-08-08 15:57 UTC, euzl commented
뒤로가기와 액티비티 이름 보이는 부분은 직접 구현하는 게 아니라, actionBar를 이용하면 되는거였군요..!!1 배워갑니다

2020-08-09 05:35 UTC, merged