Feature/splash
naccoro/WASK-Android pull request #20
Opened 2020-08-07 16:05 UTC by Gomyo

앱의 얼굴을 책임지는 Splash 입니다. 너무나 간단한 작업인데 오래 걸려 죄송합니다 ㅠㅠ

### 문제점(?)
splash.xml의 코드를 이렇게 구성했습니다.
```Java
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/splash_bg_blue"/>
    <item>
        <bitmap
            android:src="@drawable/splash_logo"
            android:gravity="center"/>
    </item>
</layer-list>
```
그런데 자료들을 찾아 보니 item의 자식으로 bitmap을 사용할 경우, ResourceNotFoundException을 발생시킬 수 있으며, 이에 따라 일부 기종에서 앱 실행과 동시에 죽어버리는 경우가 있다고도 합니다. 그래서 bitmap을 제외한,
```Java
<item
        android:src="@drawable/splash_logo"
        android:gravity="center"/>
```
이 코드로 변경해 보았는데 오히려 이렇게 하니 제 핸드폰(갤럭시 S20)에서 실행하자마자 죽더라구요? 우선 bitmap으로 구현했지만, 이후 이슈가 될 수 있을 것 같아 기록해 둡니다!

#### 문제점 관련 Reference
[링크1](https://soulduse.tistory.com/70)
[링크2](https://kjwsx23.tistory.com/254)

### 화면
아직 merge 되지 않았기 때문에 로딩 시간이 아예 없어서 화면 캡처는 하지 못했습니다.
![wask](https://user-images.githubusercontent.com/40337311/89664645-70016600-d912-11ea-93cb-66e54d73a5e2.PNG)
안드로이드 스튜디오 xml 파일의 디자인 화면으로 대체합니다.

2020-08-07 20:03 UTC, ethan-223 requested changes
말씀하신 이슈에 관련해서는 지금 하신 방법대로 하는 게 좋을 것 같습니다.
그리고 아마 스플래시 이미지는 변경될텐데(지난번에 보여드린 M , W 대칭 이미지) 그 때 수정하면서 확정해보도록 하죠 !

2020-08-07 20:03 UTC, SEONGGYU96 commented on gitmessage.txt
> +#     본문은 "어떻게" 보다 "무엇을", "왜"를 설명한다.
이건 푸쉬하지 않아도 좋을 것 같아요 !

2020-08-07 22:08 UTC, euzl requested changes
저는 지금 방식으로도 괜찮다고 생각합니다..!! 

나중에 기회가 되면 현 방식과 setTheme방식의 성능을 직접 비교해보는 것도 좋을 것 같아요.

2020-08-07 22:08 UTC, euzl commented on app/src/main/res/layout/activity_splash.xml
> +<?xml version="1.0" encoding="utf-8"?>
`activity_splash.xml`파일은 사용 되지 않는 것 같아서 삭제해도 될 것 같습니다!

2020-08-07 22:08 UTC, euzl commented on app/src/main/res/drawable/splash.xml
> +    </item>
이 부분을
```xml
<item
        android:drawable="@drawable/splash_logo"
        android:gravity="center" />
```
이렇게 한번 바꿔보세요!

2020-08-08 02:33 UTC, jaeryo2357 approved these changes
성규님과 유진님이 모두 코멘트 해주셔서 저는 더 해드릴 코멘트가 없네요.

setTheme 형식은 찾아보니 Splash 형식을 구현할 수 있는 가장 간단한 방법이라고 합니다. (android develop 기준) .  하지만 만약 Splash 화면에서 앱의 초기화, 사용자 쿠키 인식 등 작업이 이루어 진다면 Splash Activity가 따로 존재하는 것이 기능 분리에 더 좋게 보일듯 해요

2020-08-08 04:13 UTC, euzl approved these changes
splash 잘 될 것 같습니다 👍

2020-08-08 04:59 UTC, Gomyo commented on gitmessage.txt
> +#     본문은 "어떻게" 보다 "무엇을", "왜"를 설명한다.
네 삭제하겠습니다!

2020-08-08 05:03 UTC, Gomyo commented on app/src/main/res/drawable/splash.xml
> +    </item>
네 PR 메시지에 문제점(?) 부분에 기록해 두었는데, 말씀하신 대로 바꾸면 오히려 앱이 죽어버리더라구요. 우선은 bitmap으로 두고, 나중에 문제가 생기면 방안을 찾아 보겠습니다.

2020-08-08 05:03 UTC, Gomyo commented on app/src/main/res/layout/activity_splash.xml
> +<?xml version="1.0" encoding="utf-8"?>
생각해보니 삭제해도 되는군요! 삭제했습니다.

2020-08-08 05:16 UTC, Gomyo commented on app/src/main/res/drawable/splash.xml
> +    </item>
AVD ( Nexus 5X API 29) 로도 돌려 봤는데, bitmap을 없애면 앱이 바로 죽어버립니다!

2020-08-08 08:19 UTC, ethan-223 approved these changes

2020-08-08 11:43 UTC, merged

2020-08-08 16:55 UTC, euzl commented on app/src/main/res/drawable/splash.xml
> +    </item>
@Gomyo 넵 그 코드랑 비슷한데 `android:src`를 `android:drawable`로 바꾸면 잘 실행됩니다!!