refactor: splash layout
naccoro/WASK-Android pull request #28
Opened 2020-08-08 17:34 UTC by Gomyo

#### 코드 리팩토링

ResourceNotFoundException 처리를 위해 리팩토링합니다.

[참조 링크](https://kjwsx23.tistory.com/254)

2020-08-08 17:42 UTC, euzl requested changes

2020-08-08 17:42 UTC, euzl commented on app/src/main/res/drawable/splash.xml
> +            android:drawable="@drawable/splash_logo"
들여쓰기 하나 빼주세요 >< ㅋㅋㅋㅋㅋㅋㅋㅋ` shift+tab`

2020-08-08 17:42 UTC, Gomyo commented on app/src/main/res/drawable/splash.xml
> +            android:drawable="@drawable/splash_logo"
아 이런 어이없는...시정하겠습니다.

2020-08-08 17:47 UTC, euzl approved these changes
<img src="https://user-images.githubusercontent.com/37680108/89716746-94307600-d9ea-11ea-8d05-0dc9cb4f2d1e.png" width="300">

2020-08-08 18:50 UTC, ethan-223 approved these changes
와 어떻게 이렇게 코딩할 생각을 ~~!!

2020-08-09 02:07 UTC, jaeryo2357 approved these changes
너무나 좋은 개선 방향입니다

2020-08-09 02:56 UTC, merged