Feature/replace mask
naccoro/WASK-Android pull request #41
Opened 2020-08-11 16:11 UTC by SEONGGYU96

교체하기 기능을 추가하였습니다.

### 고민할 점
- `Room`에서 `Date` 형태를 저장할 수 없기 때문에 YYYY-MM-DD 형태의 문자열을 대신 사용하고 있어서 이를 가공하는 `DateUtil` 클래스 또한 사용하고 있습니다.
오늘 날짜 구하기, 오늘 날짜와 다른 날짜의 일수 차이 구하기 등의 로직은 과연 `DataUtil` 에 모두 포함되는 것이 맞을까요? 
관련된 가공 기능이 많아질 수록 `Repository`, `Util`, `Presenter` 셋 중 어디에 위치하는 것이 올바른지 애매해지고 있습니다.
현재 구현한 위치가 괜찮을까요?

- 달력을 구현하고 교체 일자를 나타내는 로직을 작성할 때, YYYY-MM-DD 의 형태를 계속 사용하면 불편할 것이라고 생각했습니다. 따라서 `ReplacementHistory` 객체는 `ID`값을 가지고 이를 `Primary key`로 사용하고 있는데, 사실 YYYY-MM-DD 또한 중복되어서는 안되고 `Primary key` 로 충분한 역할을 할 수 있습니다. 그러나 `Room`에서는 합성키를 지원하지 않아 `Primary key`를 묶어 사용하려면 `autoGerneated` 속성을 사용할 수 없습니다. (이는 `ID` 칼럼을 사용하는데 큰 제약입니다.)
    - 지금 처럼 ID 칼럼을 `Primary key`로 갖고, YYYY-MM-DD는 그냥 `Unique` 제약만 걸어두는 것이 좋을까요?
    - 아니면 ID 칼럼을 없애고 YYYY-MM-DD 값만 프라이머리 키로 갖는 것이 좋을까요?
        - 이 경우, 해당 날짜가 DB에 존재하는지 확인하는 등의 로직이 조금 더 수월해집니다. (현재는 ID 값을 빼고 비교하도록 `equare` 메서드 재작성)

로직이 복잡해지면서 코드가 약간 마음에 안들지만 어디를 콕 찝기가 어렵습니다. 피드백 난도질 부탁드립니다 !

![KakaoTalk_Image_2020-08-12-01-00-19](https://user-images.githubusercontent.com/57310034/89920336-3e044280-dc37-11ea-85ad-be74fbb7b912.gif)

2020-08-11 17:04 UTC, zoonun approved these changes

2020-08-11 17:08 UTC, zoonun approved these changes
수고하셨습니다.

ID칼럼을 없애도 무방하다고 생각합니다. 캘린더이기 때문에 ID라는 변수를 따로 둘 필요가 없어 보입니다. 말씀하신 대로 날짜를 쓰는 것이 DB를 조회할 때 훨씬 편할 것이구요.

교체 일자를 나타내는 로직을 구현할 때라 함은
**며칠째 계속 마스크를 쓰고 있는지**  의 계산을 위해 YYYY-MM-DD 값을 받아오는 것에 문제가 있다는 말씀이실까요? room에서 date 형태를 지원하지 않기 때문에요.

그렇다면 SQL 상에서 DATEDIFF 함수를 사용해 Int형으로 값을 받아오는 건 어떤가요?

2020-08-11 17:08 UTC, Gomyo commented on app/src/main/java/com/naccoro/wask/main/MainPresenter.java
> +            //Todo: 교체 기록이 없을 경우 로직 고안
저는 period의 디폴트 값을 1로 두겠다고 생각했었는데, 0을 고려해야 하나요??

2020-08-11 18:23 UTC, euzl commented on app/src/main/java/com/naccoro/wask/main/MainPresenter.java
> +            //Todo: 교체 기록이 없을 경우 로직 고안
저도 1로하면 될 것 같습니다! 원래 시작할때 설정하는기능을 넣으려 했었는데 자연스럽게 사라졌네요..! 물론 없어도 될 것 같습니다ㅋㅋㅋㅋ

2020-08-11 18:25 UTC, euzl commented on app/src/main/java/com/naccoro/wask/main/MainActivity.java
> +        Toast.makeText(this.getApplicationContext(), "교체되었습니다.", Toast.LENGTH_SHORT).show();
토스트도 함수로 분리하나요 ??

2020-08-11 18:38 UTC, euzl commented on app/src/main/java/com/naccoro/wask/utils/DateUtils.java
> +     * 오늘 날짜를 YYYYMMDD 정수형으로 가져오기
데이터 저장도 `YYYYMMDD` 이 형식으로 하면 안되나요?? (int로..?)

2020-08-11 18:54 UTC, euzl commented on app/src/main/java/com/naccoro/wask/main/MainPresenter.java
> +     * WaskDatabase에서 현재 마스크 교체 상태를 가져오는 함수
문득 현재교체상태와 오늘 갈았는지 여부도 캐시로 저장하면 어떨까라는 생각이 듭니다. 하루에 여러번 접속한다면 너무 같은 연산이 반복될 것 같아서..! 물론 하루에 한번도 들어올까말까지만요!ㅋㅋㅋㅋ

2020-08-11 18:55 UTC, euzl approved these changes
저에게는 그저 완벽한 코드로 보일 뿐...

2020-08-11 18:56 UTC, euzl commented on app/src/main/java/com/naccoro/wask/utils/DateUtils.java
> +     * 오늘 날짜를 YYYYMMDD 정수형으로 가져오기
고민점도 해결된다고 생각합니다! date형식을 지키는 이유가 있을까요?

2020-08-12 00:16 UTC, Gomyo commented on app/src/main/java/com/naccoro/wask/utils/DateUtils.java
> +     * 오늘 날짜를 YYYYMMDD 정수형으로 가져오기
> 고민점도 해결된다고 생각합니다! date형식을 지키는 이유가 있을까요?

생각해 보니 now()와 같이 데이터를 저장하는 것이 아니라면 굳이 date 형식을 지킬 필요가 없네요.

2020-08-12 02:39 UTC, jaeryo2357 requested changes
전반적으로 코드를 보니 상당히 혼자서 고민하신 흔적이 보입니다. 고생하셨습니다 ㅠㅠ

그런데 현재 날짜를 계산하는 방식에서 월이 넘어가게 되면 ERROR를 발생할 위험이 있어 보입니다!

**고민할 점**
 - 현재 말씀해주신 기능들은 `DataUtils`에 모두 모아두는 것이 좋다고 생각합니다!

 -  저는 `primary key`로 `ID`를 사용하는 것이 좋아보입니다.  나중에 WASK 앱을 버전 업을 하는 과정에서 새로운 기능들 (각 날짜별 마스크 사용시간을 관리한다거나)이 추가된다고 생각했을 때 `ID`로 관리해두는 것이 좋을 것 같습니다.

2020-08-12 02:39 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/main/MainActivity.java
> +        Toast.makeText(this.getApplicationContext(), "교체되었습니다.", Toast.LENGTH_SHORT).show();
넵! 원래 분리하는 것이 좋습니다

2020-08-12 02:39 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/main/MainPresenter.java
> +            //Todo: 교체 기록이 없을 경우 로직 고안
저는 `SplashActivity`에서나 `android.intent.action.PACKAGE_ADDED`라는 앱이 처음 설치되었을 때 호출될 때 `BroadcastReceiver`사용해서 설치 날짜를 db에 넣어주는 것도 좋아보입니다.  교체한 날짜와 오늘 날짜가 같으면 마스크는 `1일`째 사용중이니까?? 괜찮을 듯 합니다.

2020-08-12 02:39 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/main/MainPresenter.java
> +     * WaskDatabase에서 현재 마스크 교체 상태를 가져오는 함수
저도 유진님 의견에 동의합니다!

2020-08-12 02:39 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/main/MainPresenter.java
> +        return DateUtils.getTodayToInt() - DateUtils.getDateToInt(replacementHistoryRepository.getLastReplacement()) + 1;
위에 선언한 변수를 사용하면 좋을 것같아요.
`DateUtils.getDateInt(lastReplacement) + 1`

2020-08-12 02:39 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/utils/DateUtils.java
> +    public static int getDateToInt(String date) {
`20200812 - 20200729 = 83 //답은 14일 차이` 위 방식으로 날짜를 계산하는 방식을 사용하면 위 수식처럼 월이 달라지면 계산이 이상해집니다 ㅠㅠ 

```java
  GregorianCalendar init = new GregorianCalendar(2019, 9, 19, 20, 0, 0); //2019년 10월 19일 오후 8시 0분 0초
  
  GregorianCalendar now = new GregorianCalendar(); //현재
  now.set(Calendar.SECOND, 0); 

  long diff = now.getTimeInMillis() - init.getTimeInMillis();

  long sec = diff / 1000; //두 calendar가 몇 초 차이 나는 지

  long min = diff / (60 * 1000);  //두 calendar가 몇 분 차이 나는 지

  long hour = diff / (60 * 60 * 1000); //두 calendar가 몇 시간 차이 나는 지
  
  long day = diff / (24 * 60 * 60 * 1000); //두 calendar가 며칠 차이 나는 지
```
좀 더 정확한 계산을 하려면 두 객체 모두 `Calendar.MILLISECOND`을 0으로 맞추는 것이 좋습니다.

Wask에서는 `day` 변수만 사용하면 될 것 같습니다.

2020-08-12 04:23 UTC, SEONGGYU96 commented on app/src/main/java/com/naccoro/wask/main/MainPresenter.java
> +            //Todo: 교체 기록이 없을 경우 로직 고안
0은 교체 일자가 없을 때의 임시 값으로 (null 대체) 사용하였습니다 !

그리고 교체 일자가 없을 때는 어제 새벽에 디자이너와 이야기 해봤을 때는, 앱을 처음 설치했을 때 사용하고 있던 마스크가 며칠 째 사용중인지 모르는 상태에서 무작정 1일 째 사용 중이라고 뜨는 것 보다는 교체 기록이 없음을 보여주는 게 낫다고 하더군요 ! 어떠신가요?

2020-08-12 04:24 UTC, SEONGGYU96 commented on app/src/main/java/com/naccoro/wask/main/MainActivity.java
> +        Toast.makeText(this.getApplicationContext(), "교체되었습니다.", Toast.LENGTH_SHORT).show();
토스트도 뷰에 관한 로직으로 알고있씀다 !

2020-08-12 04:25 UTC, SEONGGYU96 commented on app/src/main/java/com/naccoro/wask/utils/DateUtils.java
> +     * 오늘 날짜를 YYYYMMDD 정수형으로 가져오기
그렇네요 저 왜 YYYY-MM-DD 를 고집했을까요? SQLite 에서는 "Date를 YYYY-MM-DD 형식으로 사용한다" 라는 말에 고정관념이 생겼었나봅니다 ..! 애초에 Int타입의 YYYYMMDD가 훨씬 간편해지겠네요. 수정하겠습니다 !

2020-08-12 04:27 UTC, SEONGGYU96 commented on app/src/main/java/com/naccoro/wask/main/MainPresenter.java
> +     * WaskDatabase에서 현재 마스크 교체 상태를 가져오는 함수
오 저도 동의합니다. isChanged 가 이미 역할을 하고 있으니 이걸로 우선 검사하는 로직을 삽입하면 되겠네요

2020-08-12 04:29 UTC, SEONGGYU96 commented on app/src/main/java/com/naccoro/wask/main/MainPresenter.java
> +        return DateUtils.getTodayToInt() - DateUtils.getDateToInt(replacementHistoryRepository.getLastReplacement()) + 1;
앗 안그래도 이것 때문에 변수를 따로 뒀는데 ㅋㅋㅋ 빼먹었군요 감사합니다 ㅎ

2020-08-12 04:30 UTC, SEONGGYU96 commented on app/src/main/java/com/naccoro/wask/utils/DateUtils.java
> +    public static int getDateToInt(String date) {
아 그 부분을 생각못했군요.. 굉장한 에러를 일으킬 뻔 했습니다 .. ! 레퍼런스 감사합니다. 참고하여 정교하게 작성해보겠습니다

2020-08-12 04:46 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/main/MainPresenter.java
> +            //Todo: 교체 기록이 없을 경우 로직 고안
오 교체기록이 없음이 더 좋아보입니다. 좋은 의견이에요!!

2020-08-12 13:56 UTC, euzl commented on app/src/main/java/com/naccoro/wask/main/MainPresenter.java
> +            //Todo: 교체 기록이 없을 경우 로직 고안
찬성입니다!

2020-08-12 13:56 UTC, euzl commented on app/src/main/java/com/naccoro/wask/main/MainActivity.java
> +        Toast.makeText(this.getApplicationContext(), "교체되었습니다.", Toast.LENGTH_SHORT).show();
감삼다!

2020-08-12 13:58 UTC, Gomyo commented on app/src/main/java/com/naccoro/wask/main/MainPresenter.java
> +            //Todo: 교체 기록이 없을 경우 로직 고안
저도 찬성합니다!

2020-08-13 07:27 UTC, jaeryo2357 approved these changes
수고하셨습니다!

2020-08-13 10:16 UTC, merged