Feature/notification
naccoro/WASK-Android pull request #42
Opened 2020-08-11 16:27 UTC by Gomyo

### #5 영구 notification ( foreground service) 구현

settingActivity가 말썽이네요.  
변경 사항은 72 ~ 82 라인만 보시면 됩니다.

## Index
1. 포그라운드 노티피케이션 추가
2. 노티피케이션 채널
3. 노티피케이션 선언, 실행, 외부 메서드 호출
4. 추가할 것

### 포그라운드 노티피케이션 추가

로고는 성규님이 공유하신 정사각형 로고를 사용해 보았으나, 가시성이 매우 떨어져 우선은 `ic_main_logo` **WASK** 로 두었습니다.
> Switch ON / Switch OFF  /   메인화면
<img align="left" src="https://user-images.githubusercontent.com/40337311/89921174-4f018380-dc38-11ea-8f5b-26e6b9a4ee72.png" width="30%" height="30%"/>
<img align="left" src="https://user-images.githubusercontent.com/40337311/89921176-4f9a1a00-dc38-11ea-87ff-4043cb9f6be1.png" width="30%" height="30%"/>
<img src="https://user-images.githubusercontent.com/40337311/89919740-a0a90e80-dc36-11ea-9e81-2308ff493190.png" width="30%" height="30%"/><br>

### 노티피케이션 채널
OREO (API 26) 이상에서는 채널이 필수여서 WaskApplication에 채널을 선언해 주었습니다.
```Java
private void createNotificationChannel() {
        if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O){
            NotificationChannel serviceChannel=new NotificationChannel(
                    CHANNEL_ID,
                    "Wask Service",
                    NotificationManager.IMPORTANCE_DEFAULT
            );
```

### 노티피케이션 선언, 실행, 외부 메서드 호출
마스크 착용일을 표시하기 위한 `MainPresenter` 클래스의 값을 받아오기 위해  
`getMaskPeriod()` 메서드를 private -> public static으로 변경했습니다.

foregroundService 실행 메서드의 리턴 값으로 start_not_sticky를 설정해 두었습니다.  
이 옵션을 사용하면 더이상 필요하지 않은 서비스가 계속 작동되는 것을 막을 수 있다는 장점이 있습니다. 실시간으로 데이터를 받을 필요가 없기 때문에 이 옵션을 사용하는게 좋아 보입니다.   
프로세스가 강제 종료된 이후 `onStartCommand()` 콜백 함수가 호출되어 NPE 위험이 있는 start_sticky 비교했을 때 관리가 더 편하다는 장점도 있습니다.

[started서비스 관련 정보](https://csjung.tistory.com/132)
### 추가할 것
포그라운드 서비스 자체에서 마스크를 교체하는 기능을 추가할 수도 있겠다고 생각해 TODO를 달아 두었습니다.

2020-08-11 18:14 UTC, euzl commented on app/src/main/java/com/naccoro/wask/notification/WaskService.java
> +                .setSmallIcon(R.drawable.ic_main_logo) // OREO 이상에서 mipmap 사용시 시스템 UI 에러납니다.
로고이미지는 `ImageAsset`으로 추가하면 됩니다!

2020-08-11 18:18 UTC, euzl approved these changes
워 완전 잘하셨네여👍

2020-08-12 00:09 UTC, Gomyo commented on app/src/main/java/com/naccoro/wask/notification/WaskService.java
> +                .setSmallIcon(R.drawable.ic_main_logo) // OREO 이상에서 mipmap 사용시 시스템 UI 에러납니다.
오 반영하겠습니다

2020-08-12 03:30 UTC, jaeryo2357 requested changes
전체적으로 주석을 읽어보니 꼼꼼히 찾아보신 흔적이 보입니다. 수고하셨습니다!!.

다만 `Service`에서 period를 가져오는 부분을 고쳐주세요.! `ServicePresenter`에서 현재 사용자의 사용일자를 가져와야 좋습니다. 그런데 아직 Develop에서는 미구현 상태이기 때문에 지금은 상수로 넘겨주면 될 것같습니다.

2020-08-12 03:30 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/notification/WaskService.java
> +    private int maskPeriod = mainPresenter.getMaskPeriod();
maskPeriod를 mainPresenter에서 가져오는 방법보다 Intent를 사용하는 것이 좋아보입니다

```java
@Override
    public int onStartCommand(Intent intent, int flags, int startId) {
       maskPeriod = intent.getIntExtra("maskPeriod", 1); 
       startForegroundService();

        return START_NOT_STICKY;
    }
```

2020-08-12 03:30 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
> -
헉.. SettingActivity는 또 이러네요..

2020-08-12 03:30 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/WaskApplication.java
> +            NotificationChannel serviceChannel=new NotificationChannel(
제가 복사해준 코드를 사용해주셔서 ㅋㅋㅋㅋ 띄어쓰기가 안되어있네요 죄송해요

2020-08-12 03:30 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/WaskApplication.java
> +            NotificationManager manager= getSystemService(NotificationManager.class);
여기도 띄어쓰기가 안되어있네요 죄송해요 ㅎㅎ..

2020-08-12 03:30 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/main/MainPresenter.java
> +    public static int getMaskPeriod() {
intent 객체를 사용해서 period를 사용해주세요!
이 함수는 다시 private로 변경해주세요

2020-08-12 03:30 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
> +                    Intent service = new Intent(SettingActivity.this, WaskService.class);
Intent에 period 값을 넣기 위해, MVP 구조를 위해
Service를 키고 끄는 기능을 2개의 함수로 분리하는 것이 좋아보이고 SettingPresenter db에서 값을 가져와 `isChecked` 가 `true`라면 `showForegroundAlert(3) //period가 3이라면`, `false`라면 `dismissForegroundAlert()`로 하시면 좋을 듯 합니다!!

2020-08-12 04:49 UTC, Gomyo commented on app/src/main/java/com/naccoro/wask/main/MainPresenter.java
> +    public static int getMaskPeriod() {
안그래도 이 부분이 마음에 걸렸었습니다. private으로 두고 intent로 접근하겠습니다!

혹시나 해서)
public static final 으로 지정해 두는 것은 어떤가요?

2020-08-12 04:52 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/main/MainPresenter.java
> +    public static int getMaskPeriod() {
위 함수 말씀이신가여?? 위 함수 말씀이신거면 private가 좋아보입니다 ㅜㅜ

2020-08-12 04:58 UTC, Gomyo commented on app/src/main/java/com/naccoro/wask/main/MainPresenter.java
> +    public static int getMaskPeriod() {
넵 알겠습니다 🆗

2020-08-12 15:31 UTC, Gomyo commented on app/src/main/java/com/naccoro/wask/notification/WaskService.java
> +                .setSmallIcon(R.drawable.ic_main_logo) // OREO 이상에서 mipmap 사용시 시스템 UI 에러납니다.
ic_main_logo로 notification icon 추가했습니다!

2020-08-12 17:23 UTC, Gomyo commented on app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
> +                    Intent service = new Intent(SettingActivity.this, WaskService.class);
관련 리팩토링을 해 보았습니다. 코드 리뷰와 더불어, 본문 5번을 확인해 주세요.

2020-08-12 19:39 UTC, euzl requested changes
고생하셨습니다!! 잘하신 것 같은데욥 (잘모름)

2020-08-12 19:39 UTC, euzl commented on app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
> +                    Intent service = new Intent(SettingActivity.this, WaskService.class);
제 생각에는 SettingActivity.java에
```java
private void showForegroundAlert(주기);
private void dismissForegorundAlert();
```
메서드를 만들고(SettingContract에도 선언) 이 부분에서는
```java
if (isChecked) {
    showForegroundAlert(주기);
} else {
    dismissForegroundAlert();
} 
```
이렇게 말씀하신 것 같습니다!

2020-08-12 19:39 UTC, euzl commented on app/src/main/java/com/naccoro/wask/notification/WaskService.java
> +        maskPeriod = intent.getIntExtra("maskPeriod", 1);
**[궁금/고민]** 

현재 사용기간은 계산되고 있지 않아서 임시로 '1'로 넣으신 것 같습니다.
그런데, 제 생각에는 `foreground`서비스는 매일 켜져있고 어플은 가끔 들어가기 때문에 여기서 주기가 계산되는 게 맞을 것 같습니다! 
그리고 MainActivity에서는 foreground에 저장된 maskPeriod를 가져오면 효율적일 것 같습니다.

다들 어떻게 생각하시는지요!! @Gomyo @jaeryo2357 @SEONGGYU96

2020-08-12 22:49 UTC, Gomyo commented on app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
> +                    Intent service = new Intent(SettingActivity.this, WaskService.class);
showForegroundAlert를 만들었습니다.
스위치가 꺼졌을 경우에는 전달할 값이 없으니 그냥 종료하면 된다고 생각했는데, dismiss 메서드를 사용해야 하는 다른 이유가 혹시 있을까요??

2020-08-12 22:51 UTC, Gomyo commented on app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
> +                    Intent service = new Intent(SettingActivity.this, WaskService.class);
> 제 생각에는 SettingActivity.java에
> ```java
> private void showForegroundAlert(주기);
> private void dismissForegorundAlert();
> ```
> 메서드를 만들고(SettingContract에도 선언) 이 부분에서는
> ```java
> if (isChecked) {
>     showForegroundAlert(주기);
> } else {
>     dismissForegroundAlert();
> } 
> ```
> 이렇게 말씀하신 것 같습니다!

아!!! 노티피케이션 생성 소멸자체를 클래스로 분리하면 되는군요 이해했습니다ㅋㅋ 값 넘기는것만 신경썼네요

2020-08-13 00:24 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
> +                    Intent service = new Intent(SettingActivity.this, WaskService.class);
유진님이 맞습니다!

2020-08-13 00:33 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/notification/WaskService.java
> +        maskPeriod = intent.getIntExtra("maskPeriod", 1);
오 그 부분을 생각 못했네요. 
`foreground` 서비스가 매일 켜져있기 때문에 자정이 넘어갈 때, 마스크 사용 일자도 변경시켜야 하는 군요.  자체적으로 주기가 계산되는 로직이 필요할 듯 합니다. + 자정이 넘어갈 때 호출되는 `AlarmManager`를 만들어야 겠네요.

하지만, MainActivity에서는 Model 객체에서 가져오는 것이 좋을듯합니다. 이미 **교체하기**기능을 구현하기 위해 `MainPresenter`에 Model 객체를 가지고 있기 때문에 굳이 Service에서 값을 가져올 필요가 없어보입니다. 또 Service와 Activity를 연결 시키기는 간단한 작업이 아니기 때문에 Model 객체에서 가져오는 것이 좋아보입니다.

2020-08-13 00:36 UTC, jaeryo2357 approved these changes

2020-08-13 01:13 UTC, Gomyo commented on app/src/main/java/com/naccoro/wask/setting/SettingActivity.java
> +                    Intent service = new Intent(SettingActivity.this, WaskService.class);
@jaeryo2357 @euzl 완전 이해했습니다 오늘 집가서 수정한뒤에 마지막 PR 날릴게요!

2020-08-13 01:21 UTC, Gomyo commented on app/src/main/java/com/naccoro/wask/notification/WaskService.java
> +        maskPeriod = intent.getIntExtra("maskPeriod", 1);
말씀하신대로 Service와 Activity를 연결시키는 것이 간단하게는 느껴지지 않네요!

@jaeryo2357 님, 궁금한게 있는데 MainPresenter의 getMaskPeriod가 아니라 SettingPresenter에 getMaskPeriod 메서드를 따로 만들어 쓰게 한 이유가 있을까요? 그냥 전역으로 mask 착용일 변수를 두고 가져다 쓰는 것은 어떤 문제가 있나요?

2020-08-13 01:33 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/notification/WaskService.java
> +        maskPeriod = intent.getIntExtra("maskPeriod", 1);
**준원님이 말씀해주신대로 Model class에서 전역으로 제공해준다면 사용하는 것이 무조건 좋습니다.**
```
 //Servcie, Presenter 등등 독립적으로 아래의 코드로 사용가능
   int period =  WaskDatabase.getMaskUsingPeriod();
```

하지만 Model에서 전역으로 제공해주지 않아서 `MainPresenter.getMaskPeriod()`는 단순히 Main 로직에서 사용하기 위해 선언한 함수였습니다.  MVP 구조상 MainPresenter는 MainView와 Model과의 소통으로 이루어져야 하는데 갑자기 이름 모를 class에서 MainPresenter랑 소통하는 부분은 MVP 구조상 안좋은 구조입니다.  이유는 준원님이 말씀해주신 대로 유지보수를 좋게하기 위함입니다.

만약 MainPresenter를 변경한다고 하면 MainView와 MainModel 이외에도 이름모를 class까지 신경을 써야하기 때문이에요.

2020-08-13 01:59 UTC, Gomyo commented on app/src/main/java/com/naccoro/wask/notification/WaskService.java
> +        maskPeriod = intent.getIntExtra("maskPeriod", 1);
이해했습니다. MVP는 서로 관련된 것들끼리 연결되어야 하는데 외부에서 툭 찌르면 MVP 구조를 무너뜨리고 유지보수가 어려워 지는 것이겠네요. 이해했습니다!   
지금은 마스크 착용일 변수만 연관되지만 그것이 main 로직에서 어떻게 변할지 모르니까요.

2020-08-13 02:01 UTC, jaeryo2357 commented on app/src/main/java/com/naccoro/wask/notification/WaskService.java
> +        maskPeriod = intent.getIntExtra("maskPeriod", 1);
맞습니다!!!!

2020-08-13 04:48 UTC, ethan-223 approved these changes
면밀히 보는 건 이번이 처음인데 고민하신 흔적이 상당하네요.. 여태 노티를 띄우는 것만 해봤지, 유동적인 데이터를 노티에 활용해본 적은 없는데 생각보다 상당히 복잡하네요. 기존 MVP 구조에 맞춰 끼어들기가 특히 어려웠을 것 같습니다. 코드 읽다가 개선의 여지가 보이는 부분은 조금만 내려보니 이미 다른 분들이 말씀하셨군요 ㅋㅋ 제 선에서는 더 이상 보이질 않습니다. 최종 PR 기다리겠습니다 !

2020-08-14 02:41 UTC, jaeryo2357 approved these changes
Setting 클래스들이 계속 전부 변경점으로 잡혀서 누구보다도 충돌문제로 고생하셨겠어요 ㅠㅠㅠ
수고하셨습니다.

2020-08-14 03:06 UTC, euzl commented on app/src/main/java/com/naccoro/wask/notification/WaskService.java
> +        maskPeriod = intent.getIntExtra("maskPeriod", 1);
오 알겠습니다!!

2020-08-14 03:08 UTC, euzl approved these changes
고생많으셨습니다 준원님✨

2020-08-14 06:17 UTC, merged